<?php
/** @var \Gg2\ToastMessage\Block\Message $block */
/** @var \Gg2\ToastMessage\ViewModel\Settings $settings */
$settings = $block->getViewModel();
?>
<div data-bind="scope: 'gg2ToastMessages'" data-placeholder="gg2ToastMessages"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "gg2ToastMessages": {
                            "component": "Gg2_ToastMessage/js/toast-message",
                            "settings": <?= /** @noEscape */ json_encode($settings->getSettings()); ?>
                        }
                    }
                }
            }
    }
</script>
